// maintenanceScheduler.js
// Utility functions for auto-scheduling maintenance visits

import { collection, addDoc, query, where, getDocs, deleteDoc, doc, updateDoc } from "firebase/firestore";
import { db } from "./firebase";
import moment from "moment";

/**
 * Calculate the next N maintenance visit dates based on frequency
 * @param {string} startDate - ISO date string (YYYY-MM-DD)
 * @param {string} frequency - 'weekly', 'biweekly', or 'monthly'
 * @param {number} count - Number of future dates to generate
 * @returns {Array<string>} Array of ISO date strings
 */
export function calculateMaintenanceDates(startDate, frequency, count = 12) {
  const dates = [];
  let currentDate = moment(startDate);
  
  // Determine the interval in days
  let intervalDays;
  switch (frequency) {
    case 'weekly':
      intervalDays = 7;
      break;
    case 'biweekly':
      intervalDays = 14;
      break;
    case 'monthly':
      intervalDays = 30; // Approximate monthly
      break;
    default:
      intervalDays = 14;
  }
  
  // Generate future dates
  for (let i = 0; i < count; i++) {
    dates.push(currentDate.format('YYYY-MM-DD'));
    
    if (frequency === 'monthly') {
      // For monthly, add 1 month properly (handles different month lengths)
      currentDate = currentDate.add(1, 'month');
    } else {
      // For weekly/biweekly, add days
      currentDate = currentDate.add(intervalDays, 'days');
    }
  }
  
  return dates;
}

/**
 * Create schedule entries for a maintenance contract
 * @param {Object} contract - Maintenance contract object
 * @param {number} monthsAhead - How many months ahead to schedule (default: 3)
 * @returns {Promise<number>} Number of schedules created
 */
export async function createMaintenanceSchedules(contract, monthsAhead = 3) {
  try {
    console.log(`📅 Creating maintenance schedules for ${contract.customerName}`);
    
    // Calculate how many visits to create based on frequency
    let visitsToCreate;
    switch (contract.frequency) {
      case 'weekly':
        visitsToCreate = monthsAhead * 4; // ~4 weeks per month
        break;
      case 'biweekly':
        visitsToCreate = monthsAhead * 2; // ~2 visits per month
        break;
      case 'monthly':
        visitsToCreate = monthsAhead; // 1 visit per month
        break;
      default:
        visitsToCreate = monthsAhead * 2;
    }
    
    // Get the start date (either contract start date or today if contract already started)
    const today = moment().format('YYYY-MM-DD');
    const contractStart = contract.startDate || today;
    const scheduleStartDate = moment(contractStart).isAfter(today) ? contractStart : today;
    
    // Calculate future visit dates
    const visitDates = calculateMaintenanceDates(scheduleStartDate, contract.frequency, visitsToCreate);
    
    // Filter out dates that are in the past
    const futureDates = visitDates.filter(date => moment(date).isSameOrAfter(today, 'day'));
    
    // Check which dates already have schedules
    const existingSchedules = await getExistingMaintenanceSchedules(contract.id);
    const existingDates = existingSchedules.map(s => s.startDate);
    
    // Only create schedules for dates that don't already exist
    const datesToCreate = futureDates.filter(date => !existingDates.includes(date));
    
    console.log(`   Found ${existingSchedules.length} existing schedules`);
    console.log(`   Creating ${datesToCreate.length} new schedules`);
    
    // Create schedule entries
    let createdCount = 0;
    for (const date of datesToCreate) {
      const scheduleData = {
        clientName: contract.customerName,
        customerId: contract.customerId || '',
        maintenanceContractId: contract.id,
        startDate: date,
        endDate: date,
        startTime: '08:00',
        endTime: '17:00',
        selectedCrews: [],
        assignedEmployees: [],
        status: 'scheduled',
        type: 'maintenance',
        notes: `Maintenance visit - ${contract.frequency}`,
        servicesIncluded: contract.servicesIncluded || '',
        monthlyRate: contract.monthlyRate || 0,
        createdAt: new Date().toISOString(),
        autoGenerated: true,
      };
      
      await addDoc(collection(db, 'schedules'), scheduleData);
      createdCount++;
    }
    
    console.log(`✅ Created ${createdCount} maintenance schedules`);
    return createdCount;
    
  } catch (error) {
    console.error('❌ Error creating maintenance schedules:', error);
    throw error;
  }
}

/**
 * Get existing maintenance schedules for a contract
 * @param {string} contractId - Maintenance contract ID
 * @returns {Promise<Array>} Array of existing schedule objects
 */
export async function getExistingMaintenanceSchedules(contractId) {
  try {
    const q = query(
      collection(db, 'schedules'),
      where('maintenanceContractId', '==', contractId)
    );
    
    const snapshot = await getDocs(q);
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
  } catch (error) {
    console.error('Error fetching existing schedules:', error);
    return [];
  }
}

/**
 * Delete all auto-generated schedules for a maintenance contract
 * @param {string} contractId - Maintenance contract ID
 * @returns {Promise<number>} Number of schedules deleted
 */
export async function deleteMaintenanceSchedules(contractId) {
  try {
    console.log(`🗑️ Deleting maintenance schedules for contract ${contractId}`);
    
    const existingSchedules = await getExistingMaintenanceSchedules(contractId);
    
    let deletedCount = 0;
    for (const schedule of existingSchedules) {
      // Only delete auto-generated schedules that haven't been completed
      if (schedule.autoGenerated && schedule.status !== 'completed') {
        await deleteDoc(doc(db, 'schedules', schedule.id));
        deletedCount++;
      }
    }
    
    console.log(`✅ Deleted ${deletedCount} schedules`);
    return deletedCount;
    
  } catch (error) {
    console.error('❌ Error deleting schedules:', error);
    throw error;
  }
}

/**
 * Update maintenance schedules when contract is paused/cancelled
 * @param {string} contractId - Maintenance contract ID
 * @param {string} status - New status ('paused' or 'cancelled')
 */
export async function updateMaintenanceScheduleStatus(contractId, status) {
  try {
    const existingSchedules = await getExistingMaintenanceSchedules(contractId);
    
    for (const schedule of existingSchedules) {
      // Only update future auto-generated schedules
      if (schedule.autoGenerated && moment(schedule.startDate).isAfter(moment())) {
        const newStatus = status === 'cancelled' ? 'cancelled' : 'paused';
        await updateDoc(doc(db, 'schedules', schedule.id), {
          status: newStatus,
          updatedAt: new Date().toISOString(),
        });
      }
    }
    
    console.log(`✅ Updated schedule status to ${status}`);
  } catch (error) {
    console.error('Error updating schedule status:', error);
    throw error;
  }
}

/**
 * Get the next scheduled visit date for a contract
 * @param {string} contractId - Maintenance contract ID
 * @returns {Promise<string|null>} Next visit date (YYYY-MM-DD) or null
 */
export async function getNextVisitDate(contractId) {
  try {
    const schedules = await getExistingMaintenanceSchedules(contractId);
    
    // Filter to future schedules that aren't cancelled
    const futureSchedules = schedules
      .filter(s => {
        return moment(s.startDate).isSameOrAfter(moment(), 'day') && 
               s.status !== 'cancelled' &&
               s.status !== 'completed';
      })
      .sort((a, b) => moment(a.startDate).diff(moment(b.startDate)));
    
    return futureSchedules.length > 0 ? futureSchedules[0].startDate : null;
    
  } catch (error) {
    console.error('Error getting next visit date:', error);
    return null;
  }
}

/**
 * Regenerate schedules for active contracts (called when a visit is completed)
 * @param {string} contractId - Maintenance contract ID
 * @param {Object} contract - Full contract object
 */
export async function regenerateMaintenanceSchedules(contractId, contract) {
  try {
    console.log(`🔄 Regenerating schedules for ${contract.customerName}`);
    
    // Get existing schedules
    const existingSchedules = await getExistingMaintenanceSchedules(contractId);
    const futureSchedules = existingSchedules.filter(s => 
      moment(s.startDate).isAfter(moment()) && 
      s.status !== 'cancelled' &&
      s.status !== 'completed'
    );
    
    // Calculate how many more we need to maintain 3 months ahead
    let targetVisits;
    switch (contract.frequency) {
      case 'weekly':
        targetVisits = 12; // 3 months * 4 weeks
        break;
      case 'biweekly':
        targetVisits = 6; // 3 months * 2 visits
        break;
      case 'monthly':
        targetVisits = 3; // 3 months * 1 visit
        break;
      default:
        targetVisits = 6;
    }
    
    const visitsNeeded = targetVisits - futureSchedules.length;
    
    if (visitsNeeded > 0) {
      console.log(`   Need to create ${visitsNeeded} more visits`);
      
      // Get the last scheduled date
      const lastScheduledDate = futureSchedules.length > 0
        ? futureSchedules.sort((a, b) => moment(b.startDate).diff(moment(a.startDate)))[0].startDate
        : moment().format('YYYY-MM-DD');
      
      // Calculate next dates starting from day after last scheduled
      const startDate = moment(lastScheduledDate).add(1, 'day').format('YYYY-MM-DD');
      const newDates = calculateMaintenanceDates(startDate, contract.frequency, visitsNeeded);
      
      // Create new schedules
      for (const date of newDates) {
        const scheduleData = {
          clientName: contract.customerName,
          customerId: contract.customerId || '',
          maintenanceContractId: contractId,
          startDate: date,
          endDate: date,
          startTime: '08:00',
          endTime: '17:00',
          selectedCrews: [],
          assignedEmployees: [],
          status: 'scheduled',
          type: 'maintenance',
          notes: `Maintenance visit - ${contract.frequency}`,
          servicesIncluded: contract.servicesIncluded || '',
          monthlyRate: contract.monthlyRate || 0,
          createdAt: new Date().toISOString(),
          autoGenerated: true,
        };
        
        await addDoc(collection(db, 'schedules'), scheduleData);
      }
      
      console.log(`✅ Created ${visitsNeeded} new schedules`);
    } else {
      console.log(`   Already have enough future visits scheduled`);
    }
    
  } catch (error) {
    console.error('Error regenerating schedules:', error);
    throw error;
  }
}